proxy:
        secretToken: "MySecretToken"
        service:
                type: NodePort
hub:
        cookieSecret: "MyCookieSecret"
        db:
                type: sqlite-memory
                
auth:
        type: github
        github:
                clientId: "my.clientId"
                clientSecret: "my.clientSecret"
                callbackUrl: "http://<my.host.address>/hub/oauth_callback"

singleuser:
        storage:
                type: none
        memory:
                guarantee: 1G
                limit: 1G
        cpu:
                guarantee: 1
                limit: 1
ingress:
  enabled: true
  hosts:
  - localhost
  - <my.host.address>
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 16m
    ingress.kubernetes.io/proxy-read-timeout: 3600
    ingress.kubernetes.io/proxy-send-timeout: 3600
    kubernetes.io/tls-acme: 'true'
  tls:
  - hosts:
    -  <my.host.address>



